prefix=/usr/local
exec_prefix=$(prefix)
bindir=$(exec_prefix)/bin
datadir=$(prefix)/share
libdir=$(exec_prefix)/lib
infodir=$(prefix)/info
includedir=$(prefix)/include
docdir=$(datadir)/doc

INSTALL=install
INSTALL_DATA=$(INSTALL) --mode 644
INSTALL_PROGRAM=$(INSTALL)

install-strip:
	$(MAKE) INSTALL_PROGRAM='$(INSTALL_PROGRAM) --strip' install
